[package]
name = "vergil"
version = "0.1.1"
edition = "2021"
authors = ["Zahash <zahash.z@gmail.com>"]
description = "Vergil!"
license = "MIT"
repository = "https://github.com/zahash/vergil"

[dependencies]
